def INF():
    print('------------------------------------------------------------------------------------------------------------')
    skils_2 = ['Медленно поливает', 'Медленно копает', 'Неумеет торговаться', 'Плохо ухаживает за животными', 'Много выпивает', 'Нету Водительского удостоверения']
    skils_1 = ['Быстро поливает', 'Быстро копает', 'Умеет торговаться', 'Хорошо ухаживает за животными', 'Мало выпивает', 'Есть Водительское удостоверение']
    x = 1
    list1 = ['Игнат', 'Катюха', 'Митяй', 'Виталий', 'Лерок']
    print('Команда ЛУШИХ фермеров России:')
    print('-' * 108)
    for i in list1:
        print(str(x) + ')', i)
        x +=1
    print('-' * 108)
    infor = input('Чтобы узнать побробную информацию выберете порядковый номер человека - ')
    if '1' in infor:
        print('-' * 108)
        print(list1[0], '- Самый главный на селе (СЫН ФЕРМЕРА)')
        print('-' * 108)
        print('+', skils_1[0])
        print('+', skils_1[2])
        print('+', skils_1[5])
        print('-' * 108)
        print('-', skils_2[4])
        print('-', skils_2[3])
        print('-', skils_2[1])
    if '2' in infor:
        print('-' * 108)
        print(list1[1], '- Самая красивая девушка на селе!')
        print('-' * 108)
        print('+', skils_1[4])
        print('-' * 108)
        print('-', skils_2[0])
        print('-', skils_2[2])
        print('-', skils_2[1])
        print('-', skils_2[3])
        print('-', skils_2[5])
    if '3' in infor:
        print('-' * 108)
        print(list1[2], '- Золотые руки села!')
        print('-' * 108)
        print('+', skils_1[1])
        print('+', skils_1[0])
        print('+', skils_1[2])
        print('+', skils_1[3])
        print('+', skils_1[5])
        print('-' * 108)
        print('-', skils_2[4])
    if '4' in infor:
        print('-' * 108)
        print(list1[3], '- Торгует на базаре (Выдумывает себе друзей)')
        print('-' * 108)
        print('+', skils_1[1])
        print('+', skils_1[3])
        print('+', skils_1[2])
        print('+', skils_1[5])
        print('-' * 108)
        print('-', skils_2[4])
        print('-', skils_2[0])
    if '5' in infor:
        print('-' * 108)
        print(list1[4], '- Самая милая и ответсвенная девочка на селе!')
        print('-' * 108)
        print('+', skils_1[0])
        print('+', skils_1[1])
        print('+', skils_1[2])
        print('+', skils_1[3])
        print('+', skils_1[4])
        print('-' * 108)
        print('-', skils_2[5])